AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Music Playlist Service

Globals:
  Function:
    Timeout: 20

Resources:

  AccessDynamoDBTablesRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
      AssumeRolePolicyDocument:
        Version: "2012-10-17" 
        Statement: 
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'WriteToCloudWatch'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudwatch:PutMetricData
              Resource: '*'
        - PolicyName: 'AccessPlaylistsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource: 
                Fn::Join:
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':table/playlists'
        - PolicyName: 'AccessAlbumTracksTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource: 
                Fn::Join:
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':table/album_tracks'

  GetPlaylistLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessDynamoDBTablesRole.Arn
      CodeUri: MusicPlaylistServiceLambda
      Handler: com.nashss.se.musicplaylistservice.lambda.GetPlaylistLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        SustainableShipmentService:
          Type: Api
          Properties:
            Path: /playlists/{id}
            Method: get

  #-----------------------------------------------------------------
  
  PlaylistsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "playlists"

  AlbumTracksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "asin"
          AttributeType: "S"
        - AttributeName: "track_number"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "asin"
          KeyType: "HASH"
        - AttributeName: "track_number"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "album_tracks"

